"""Add content column to Answer table

Revision ID: 82b9b00ae984
Revises: 13b2f6734cc0
Create Date: 2023-12-19 13:45:56.474695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b9b00ae984'
down_revision = '13b2f6734cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
